### ISSUE TITLE
Argument of type 'AxiosInstance' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'

### ISSUE THREAD

**Issue by nwaughachukwuma** [softonic/axios-retry#159]
When I try to configure axiosRetry using an axios client as specified in the usage section of the [README](https://github.com/softonic/axios-retry#usage)

```ts
// Works with custom axios instances
const client = axios.create({ baseURL: 'http://example.com' });
axiosRetry(client, { retries: 3 });
```

I get the following error:
> Argument of type 'AxiosInstance' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'

Setup Info:
Platform: `macOS Mojave v10.14.6`
Typescript: `v4.1.2`
Node.js: `v12.18.3`

**Comment by hugebdu** [comment]
same here.

Platform: macOS Cataline v10.15.7
Typescript: v3.9.7
Node.js: v12.19.0

**Comment by kmeshavkin** [comment]
I had that problem too - in my case it was old version of axios that caused this error (I had `v0.18.1`).

I also have yarn workspaces set up and axios was listed in one of workspace's `package.json` as `v0.21.1` (last version currently), but main `node_modules` still resolved to `v0.18.1` (probably due to some other dependency), so I added this to main `package.json` and now error is fixed:
```json
"resolutions": {
  "axios": "0.21.1"
}
```

**Comment by wjureczka** [comment]
Hi there!
I have the same problem:
Node.js: 14.15.2
TypeScript: 4.2.4
Platform: macOS

package.json:
`       
 "axios": "0.19.2",
 "axios-hooks": "2.7.0",
 "axios-retry": "3.2.0",
`
![image](https://user-images.githubusercontent.com/24592871/136770145-6beda4fd-70bf-4977-a835-68bbf029cbb5.png)

**Comment by xisvaldo** [comment]
Hello, same error here, any updates?

Node.JS 16.13.1
TypeScript 4.6.2
Axios 0.24.0
Axios Retry 3.2.4
Linux

**Comment by shaunkh** [comment]
Was this ever solved? @rubennorte

**Comment by M4FFS** [comment]
+1

**Comment by yatishhr** [comment]
+1

**Comment by matsgm** [comment]
I had same error with:
```
"axios": "^1.4.0",
"axios-retry": "^3.4.0"
```
Added:
```
"resolutions": {
    "axios": "1.4.0"
}
```

which fixed it.

**Comment by viktornord** [comment]
This is still an issue, please fix it

**Comment by yutak23** [comment]
Sorry if I am wrong. I hope this is of some help to you.

It may be due to a different version of axios.
I think this may happen when multiple versions of axios are under node_modules due to dependencies.

```ts
import axiosRetry, { exponentialDelay } from 'axios-retry'; // <- version of axios on which the type definition depends is 1.2.3
import axios from 'axios'; // <- this axios is 1.4.0

axiosRetry(axios, { retryDelay: exponentialDelay }); // compile error
```

My full error logs is below.

```console
$ npx tsc
index.ts:4:12 - error TS2345: Argument of type 'AxiosStatic' is not assignable to parameter of type 'AxiosInstance | AxiosStatic'.
  Type 'AxiosStatic' is not assignable to type 'AxiosInstance'.
    Types of property 'defaults' are incompatible.
      Type 'Omit<import("/home/study/workspace/axios-retry/spec/typings/cjs/node_modules/axios/index").AxiosDefaults<any>, "headers"> & { headers: import("/home/study/workspace/axios-retry/spec/typings/cjs/node_modules/axios/index").HeadersDefaults & { ...; }; }' is not assignable to type 'Omit<import("/home/study/workspace/axios-retry/node_modules/axios/index").AxiosDefaults<any>, "headers"> & { headers: import("/home/study/workspace/axios-retry/node_modules/axios/index").HeadersDefaults & { ...; }; }'.
        Type 'Omit<AxiosDefaults<any>, "headers"> & { headers: HeadersDefaults & { [key: string]: AxiosHeaderValue; }; }' is not assignable to type 'Omit<AxiosDefaults<any>, "headers">'.
          Types of property 'transformRequest' are incompatible.
            Type 'import("/home/study/workspace/axios-retry/spec/typings/cjs/node_modules/axios/index").AxiosRequestTransformer | import("/home/study/workspace/axios-retry/spec/typings/cjs/node_modules/axios/index").AxiosRequestTransformer[]' is not assignable to type 'import("/home/study/workspace/axios-retry/node_modules/axios/index").AxiosRequestTransformer | import("/home/study/workspace/axios-retry/node_modules/axios/index").AxiosRequestTransformer[]'.
              Type 'AxiosRequestTransformer' is not assignable to type 'AxiosRequestTransformer | AxiosRequestTransformer[]'.
                Type 'import("/home/study/workspace/axios-retry/spec/typings/cjs/node_modules/axios/index").AxiosRequestTransformer' is not assignable to type 'import("/home/study/workspace/axios-retry/node_modules/axios/index").AxiosRequestTransformer'.
                  The 'this' types of each signature are incompatible.
                    Type 'AxiosRequestConfig<any>' is not assignable to type 'InternalAxiosRequestConfig<any>'.
                      Types of property 'headers' are incompatible.
                        Type 'import("/home/study/workspace/axios-retry/node_modules/axios/index").AxiosRequestHeaders' is not assignable to type 'import("/home/study/workspace/axios-retry/spec/typings/cjs/node_modules/axios/index").AxiosRequestHeaders'.
                          Type 'AxiosRequestHeaders' is not assignable to type 'Partial<RawAxiosHeaders & { Accept: AxiosHeaderValue; "Content-Length": AxiosHeaderValue; "User-Agent": AxiosHeaderValue; "Content-Encoding": AxiosHeaderValue; Authorization: AxiosHeaderValue; } & { ...; }>'.
                            'string' index signatures are incompatible.
                              Type 'AxiosHeaderValue' is not assignable to type 'import("/home/study/workspace/axios-retry/spec/typings/cjs/node_modules/axios/index").AxiosHeaderValue'.
                                Type 'AxiosHeaders' is not assignable to type 'AxiosHeaderValue'.
                                  Type 'AxiosHeaders' is missing the following properties from type 'AxiosHeaders': setAuthorization, getAuthorization, hasAuthorization, [Symbol.iterator]

4 axiosRetry(axios, { retryDelay: exponentialDelay });
             ~~~~~

Found 1 error in index.ts:4
```

**Comment by razor-x** [comment]
Started getting this after updating from Axios 1.5 to 1.6. Probably related to https://github.com/axios/axios/pull/5931/files

**Comment by yutak23** [comment]
I have looked into the details of this compile error.

### Problem

Since we are using one index.d.ts in axios-retry, it is the same index.d.ts for both ES Module and CommonJS. In other words, the type definition of axios imported by `import * as axios from 'axios';` will be `index.d.cts`.

Specifically, `module "/home/study/workspace/ts-node-oidc/node_modules/axios/index"` means that axios-retry is a CommonJS package, so `node_modules/ axios/index.d.cts`, since axios-retry is a CommonJS package.

This will be the same whether the project using axios-retry is configured for ES Module or CommonJS.
![image](https://github.com/softonic/axios-retry/assets/79501292/6f552e73-c821-4e7e-9aa7-56fb7c12aa09)

And the trouble is that axios `index.d.cts` (type definitions for CommonJS) and `index.d.ts` (type definitions for ES Module) are incompatible.

This causes the following compile error.

```
$ npx tsc
srv/app.ts:7:12 - error TS2345: Argument of type 'AxiosStatic' is not assignable to parameter of type 'AxiosStatic | AxiosInstance'.
  Type 'import("/home/study/workspace/ts-node-oidc/node_modules/axios/index", { assert: { "resolution-mode": "import" } }).AxiosStatic' is not assignable to type 'import("/home/study/workspace/ts-node-oidc/node_modules/axios/index").AxiosStatic'.
    Types of property 'create' are incompatible.
      Type '(config?: import("/home/study/workspace/ts-node-oidc/node_modules/axios/index", { assert: { "resolution-mode": "import" } }).CreateAxiosDefaults<any> | undefined) => import("/home/study/workspace/ts-node-oidc/node_modules/axios/index", { assert: { "resolution-mode": "import" } }).AxiosInstance' is not assignable to type '(config?: import("/home/study/workspace/ts-node-oidc/node_modules/axios/index").CreateAxiosDefaults<any> | undefined) => import("/home/study/workspace/ts-node-oidc/node_modules/axios/index").AxiosInstance'.
        Types of parameters 'config' and 'config' are incompatible.
          Type 'import("/home/study/workspace/ts-node-oidc/node_modules/axios/index").CreateAxiosDefaults<any> | undefined' is not assignable to type 'import("/home/study/workspace/ts-node-oidc/node_modules/axios/index", { assert: { "resolution-mode": "import" } }).CreateAxiosDefaults<any> | undefined'.
            Type 'import("/home/study/workspace/ts-node-oidc/node_modules/axios/index").CreateAxiosDefaults<any>' is not assignable to type 'import("/home/study/workspace/ts-node-oidc/node_modules/axios/index", { assert: { "resolution-mode": "import" } }).CreateAxiosDefaults<any>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
              Types of property 'headers' are incompatible.
                Type 'AxiosHeaders | Partial<import("/home/study/workspace/ts-node-oidc/node_modules/axios/index").HeadersDefaults> | Partial<RawAxiosHeaders & { ...; } & { ...; }>' is not assignable to type 'import("/home/study/workspace/ts-node-oidc/node_modules/axios/index", { assert: { "resolution-mode": "import" } }).AxiosHeaders | Partial<import("/home/study/workspace/ts-node-oidc/node_modules/axios/index", { assert: { "resolution-mode": "import" } }).HeadersDefaults> | Partial<...>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
                  Type 'Partial<HeadersDefaults>' is not assignable to type 'AxiosHeaders | Partial<HeadersDefaults> | Partial<RawAxiosHeaders & { Accept: AxiosHeaderValue; "Content-Length": AxiosHeaderValue; "User-Agent": AxiosHeaderValue; "Content-Encoding": AxiosHeaderValue; Authorization: AxiosHeaderValue; } & { ...; }>' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
                    Type 'Partial<HeadersDefaults>' is not assignable to type 'Partial<RawAxiosHeaders & { Accept: AxiosHeaderValue; "Content-Length": AxiosHeaderValue; "User-Agent": AxiosHeaderValue; "Content-Encoding": AxiosHeaderValue; Authorization: AxiosHeaderValue; } & { ...; }>'.
                      Property 'common' is incompatible with index signature.
                        Type 'Partial<RawAxiosHeaders & { Accept: AxiosHeaderValue; "Content-Length": AxiosHeaderValue; "User-Agent": AxiosHeaderValue; "Content-Encoding": AxiosHeaderValue; Authorization: AxiosHeaderValue; } & { ...; }>' is not assignable to type 'AxiosHeaderValue | undefined'.
                          Type 'Partial<RawAxiosHeaders & { Accept: AxiosHeaderValue; "Content-Length": AxiosHeaderValue; "User-Agent": AxiosHeaderValue; "Content-Encoding": AxiosHeaderValue; Authorization: AxiosHeaderValue; } & { ...; }>' is missing the following properties from type 'string[]': length, pop, push, concat, and 29 more.

7 axiosRetry(axios, { retries: 3 });
             ~~~~~


Found 1 error in srv/app.ts:7
```

### Solution

It would be quite difficult to modify `index.d.ts` and `index.d.cts` in axios to be compatible, so I think it would be better to change the export of type definitions in axios-retry, depending on whether it is ES Module or CommonJS.

**Comment by yuvall-cyera** [comment]
Hello
Do you know when you'll release a new version with this fix?
Snyk currently warns about older axios versions and an upgrade to 1.6.0 should be done
https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

**Comment by mindhells** [comment]
> Hello Do you know when you'll release a new version with this fix? Snyk currently warns about older axios versions and an upgrade to 1.6.0 should be done https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

the fix for this issue is already available in 3.9.0 thanks to @yutak23

**Comment by mindhells** [comment]
Reopened because the #250 has been reverted in 3.9.1

The plan is now to migrate to TS implementation

**Comment by mindhells** [comment]
This should be fixed in v4.0.0

**Comment by OndrejHradecny** [comment]
Any update?

**Comment by amiram** [comment]
Still happens:
axios 1.7.7
axios-retry 4.5.0
typescript 5.6.3

"type": "module"

tsconfig:
```
{
  "compilerOptions": {
    "module": "es6",
    "target": "ES2023",
    "sourceMap": true,
    "jsx": "react",
    "moduleResolution": "node",
    "declaration": false,
    "allowSyntheticDefaultImports": true,
    "lib": [
      "ES2023",
      "dom",
      "dom.iterable"
    ]
  }
}
```

Error in:
```
import axios from 'axios';
import axiosRetry, { exponentialDelay } from 'axios-retry';

const request = axios.create({
    adapter: location.protocol !== 'https:' ? 'fetch' : undefined
});

axiosRetry(request, {
    retryCondition: error => {
        {...}
        return true;
    },
    retryDelay: exponentialDelay
});
```

**Workaround:** Use typescript 5.5.4

**Comment by GuyAgiv** [comment]
In lower Ts versions it seems that the ts engine is not "smart enough" to discover this error.
Is there any suggestions how to fix this issue except casting the axiosinstance as any?

**Comment by chris-tuncap** [comment]
+1

**Comment by kmart-ianharley** [comment]
Found a fix for this issue in the [axios repo](https://github.com/ctimmerm/axios-mock-adapter/issues/400#issuecomment-2907629059)
Credit to @fregante

Update `paths` in tsconfig.json


```
"compilerOptions": { 
    "paths": {  
        "axios": ["./node_modules/axios/index.d.ts"]  
    }
}
```
