### ISSUE TITLE
BUG 3.1.7 is giving me a TS error on exported members

### ISSUE THREAD

**Issue by Primajin** [softonic/axios-retry#132]
before v. 3.1.7 I had my import working like this without a problem:

```js
import axiosRetry, { isNetworkOrIdempotentRequestError } from 'axios-retry';
```

Now I get the error:

```shell
error TS2614: Module '"../node_modules/axios-retry"' has no exported member 'isNetworkOrIdempotentRequestError'. Did you mean to use 'import isNetworkOrIdempotentRequestError from "../node_modules/axios-retry"' instead?
```

**Comment by mawrkus** [comment]
@balassit @strdr4605 @EdenGottlieb any idea why would this be happening?

**Comment by Primajin** [comment]
So it still works in 3.1.6 - so the bug must be in the diff :wink:

**Comment by strdr4605** [comment]
The idea is that in `v3.1.6` 
https://github.com/softonic/axios-retry/blob/v3.1.6/index.d.ts#L53
```ts
interface IAxiosRetry {
  (
    axios: axios.AxiosStatic | axios.AxiosInstance,
    axiosRetryConfig?: IAxiosRetry.IAxiosRetryConfig
  ): void;

  isNetworkError(error: Error): boolean;
  isRetryableError(error: Error): boolean;
  isSafeRequestError(error: Error): boolean;
  isIdempotentRequestError(error: Error): boolean;
  isNetworkOrIdempotentRequestError(error: Error): boolean;
  exponentialDelay(retryNumber: number): number;
}

declare const axiosRetry: IAxiosRetry;

export = axiosRetry;
```
means that all props from `axiosRetry` are exported. See [export = and import = require()](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require).

In `v3.1.7` only 2 things are exported
https://github.com/softonic/axios-retry/blob/v3.1.7/index.d.ts#L51

```ts
declare const axiosRetry: IAxiosRetry;

export type IAxiosRetryConfig = IAxiosRetry.IAxiosRetryConfig;

export default axiosRetry;
```
So only default export and `IAxiosRetryConfig` are available.

`isNetworkOrIdempotentRequestError` and other functions should be exported explicitly in this case.

**Comment by balassit** [comment]
Yeah @strdr4605 is correct. My mistake when testing as I only used the functions by referencing `axiosRetry`. IAxiosRetry is not exported or its inner functions. I opened a #133 to export the functions but was not sure if IAxiosRetry should be.

**Comment by mawrkus** [comment]
#133 has been merged and v3.1.8 published. @Primajin can you confirm the error is fixed?

**Comment by Primajin** [comment]
Yes perfect folks! 3.1.8 passes without any warning for me - thank you very much!

**Comment by mawrkus** [comment]
Thank you guys, really appreciated your help on this because my knowledge of TS is really really limited. Have a nice week-end!
